name: Local Setup Test
on: [push]
jobs:
  mac_nix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"
      - name: Install Python Dependencies
        run: |
          poetry install
      - name: Run style and type checks
        run: |
          poetry run ruff format && poetry run ruff check
          poetry run mypy --ignore-missing-imports --disallow-untyped-calls --disallow-untyped-defs --disallow-incomplete-defs \
            data_transformations tests
      - name: Run local unit tests
        run: |
          poetry run python -m pytest tests/unit
      - name: Run local integration tests
        run: |
          poetry run python -m pytest tests/integration
